[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build]
target = "riscv64gc-unknown-none-elf"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
